User:
  name: Aquiles

Params:
  resistance: 100ohm
  port: /dev/cu.usbmodem14301  # COM3  COM5....
  device_type: dummy #(Or real) python -m serial.tools.list_ports


Scan:
  start: 0V
  stop: 3300mV
  step: 100mV
  delay: 50ms
  channel_in: 0
  channel_out: 0


Saving:
  filename: IV_data
  path : /users/sylvaingennaro/PycharmProjects/LMU_04_19/
